version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci --include=dev
      - echo "Generating .env from whitelist..."
      - rm -f .env
      - |
        while IFS= read -r var_name; do
          if [[ -n "${!var_name}" ]]; then
            echo "$var_name=\"${!var_name}\"" >> .env  
          else
            echo "$var_name=\"\"" >> .env  
            # echo "Warning: Environment variable '$var_name' not found or is empty."
          fi
        done < .env.whitelist
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Deploying to Lambda...
      - npm run deploy:${STAGE}

cache:
  paths:
    - node_modules
