version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm ci
      - printenv | grep -vE '^(HOME|PATH|PWD|SHLVL|_|LANG|TERM|HOSTNAME)' > .env
  build:
    commands:
      - echo Building application...
      - npm run build
  post_build:
    commands:
      - echo Deploying to Lambda...
      - npm run deploy:${STAGE}

cache:
  paths:
    - node_modules
